### ISSUE TITLE
Reorganize Repo into smaller metapackages

### ISSUE THREAD

**Issue by wmmc88** [uwrobotics/uwrt_mars_rover#102]
We want to clean up the organization of our ROS repository:

- **uwrt_mars_rover**:
  - **uwrt_mars_rover_arm**:
    - **uwrt_mars_rover_arm_controllers**:
      - cartesian_controller
      - preset_pose_controller
    - uwrt_mars_rover_arm_hw
    - uwrt_mars_rover_arm_msgs
  - **uwrt_mars_rover_autonomy**:
    - **uwrt_mars_rover_autonomy_controllers**:
      - neopixel_controller
      - led_matrix_controller
    - uwrt_mars_rover_autonomy_hw
    - uwrt_mars_rover_autonomy_msgs
  - **uwrt_mars_rover_drivetrain**:
    - **uwrt_mars_rover_drivetrain_controllers**:
      - diff_drive_position_controller
    - uwrt_mars_rover_drivetrain_hw
    - uwrt_mars_rover_drivetrain_msgs
  - **uwrt_mars_rover_science**:
    - **uwrt_mars_rover_science_controllers**:
      - geneva_indexer_controller
    - uwrt_mars_rover_science_hw
  - uwrt_mars_rover_bringup
  - uwrt_mars_rover_description -> this contains all the urdfs and launch files for urdfs
  - uwrt_mars_rover_control -> contains all high level ros_control stuff. (ie. combined robot hw node + control loop + high level launch w/ config selection) 
  - uwrt_mars_rover_utils -> will contain uwrt_mars_rover_hw_bridge library

**bold is metapkg**. This will be tackled in smaller prs.

------------------------------------------------------------------------------------------------------------------------------------------------------

- [ ] port neopixel to roscontrol interface, move neopixel msgs to autonomy_msgs pkg, remove top level msgs pkg

**Comment by wmmc88** [comment]
@azumnanji @hamzaMahdi @akeaveny @younesr1 
any thoughts or additions?

**Comment by akeaveny** [comment]
Where will the msgs sit?
Also, I have uwrt_arm_rover_simulation pkg in uwrt_arm rn.

**Comment by wmmc88** [comment]
@akeaveny what does the sim package contain? could it just be merged into a top level sim @azumnanji ?

i think for msgs, if we're doing this smaller metapkg thing, we have msgs split into their respective subsystem metapkg

**Comment by akeaveny** [comment]
The sim pkg contains some basic launch files for gazebo config (e.g. spawn for x, y, yaw, etc..).

**Comment by azumnanji** [comment]
sim pkg could be at top level - should have no effect on aidan's current package

**Comment by wmmc88** [comment]
@azumnanji is it ok to have a standalone arm urdf in uwrt_mars_rover/uwrt_mars_rover_arm/uwrt_mars_rover_arm_description and then pull in that urdf in the top level description pkg (uwrt_mars_rover/uwrt_mars_rover_description)?

**Comment by wmmc88** [comment]
layout for this issue has been merged in #108. leaving this issue pinned for now as a reference for developing the packages (some are just empty placeholder folders rn.)
